### ISSUE TITLE
Failed to resolve NormalizedArtifact on build server

### ISSUE THREAD

**Issue by jrduncans** [heremaps/here-sbt-bom#20] opened 2024-05-15 17:11 UTC
I'm seeing the same issue as #7 but only on my build server, not locally:

```
java.lang.RuntimeException: Failed to resolve NormalizedArtifact(org.apache.pekko,pekko-http-bom_2.13,1.0.1)
	at scala.sys.package$.error(package.scala:30)
	at com.here.bom.internal.BomReader.$anonfun$readPom$1(BomReader.scala:69)
```

Unfortunately I can't seem to find any additional info to help debug this. Would it be possible to add some debug logging to show URLs being tried or something?

**Comment by molekyla** [comment] 2024-05-16 05:42
As of now the only way is to specify `--debug` flag for `sbt` command. For example `sbt package --debug`

**Comment by jrduncans** [comment] 2024-05-16 05:51
Unfortunately, it didn't add any useful information.

**Comment by molekyla** [comment] 2024-05-16 06:23
Plugin tries to find pom in using path `{ivy.home}/cache/org.apache.pekko/pekko-http-bom_2.13/ivy-1.0.1.xml.original` (see [implementation](https://github.com/heremaps/here-sbt-bom/blob/8ed583bbf79d6948350ab26e347e716efcd02e11/plugin/src/main/scala/com/here/bom/internal/IvyPomLocator.scala#L104))
Try to get the content of this file and check if is it present and correct
Also, we will improve debug logging in future release, but there is no ETA available for this improvement

**Comment by molekyla** [comment] 2024-06-12 13:36
@jrduncans Hi. Sorry for such a big delay. We have noticed that this issue might be caused by parameters `-Dsbt.global.base=sbt-cache/sbtboot -Dsbt.boot.directory=sbt-cache/boot -Dsbt.ivy.home=sbt-cache/ivy`. If it applicable to your case, please try to build without these params
In any case we will fix this behaviour in future

**Comment by molekyla** [comment] 2024-07-05 07:30
Seems the issue might be caused by https://github.com/sbt/sbt/issues/1894

**Comment by molekyla** [comment] 2024-07-08 13:50
It should be fixed by the PR https://github.com/heremaps/here-sbt-bom/pull/22. Closing the issue

**Closed by molekyla** 2024-07-08 13:50 UTC
